POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Juliana Fajardini",
    "email": "ju@gmail.com",
    "password": "123456"
}

###
# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "ju@gmail.com",
    "password": "123456"
}

###
@token = {{login.response.body.token}}
GET http://localhost:3003/user/profile
Authorization: {{token}}

###
@token = {{login.response.body.token}}
GET http://localhost:3003/user/2e2b8043-1329-40f0-8045-cdf5544f1a4b
Authorization: {{token}}

###
@token = {{login.response.body.token}}
POST http://localhost:3003/user/recipe
Content-Type: application/json
Authorization: {{token}}

{
    "title": "Bolo de cenoura",
    "description": "Massa do Bolo"
}

### 
@token = {{login.response.body.token}}
GET http://localhost:3003/recipe/2eda2023-ac68-426a-801f-f680e0ff85b7
Authorization: {{token}}