GET http://localhost:3003/actor/gender

###

GET http://localhost:3003/movie/search?name=matrix

###

POST http://localhost:3003/actor/create
Content-Type: application/json

{
    "name": "Keanu Reeves",
    "salary": 2000000,
    "birthDate": "1964-09-10",
    "gender": "male"
}

###

POST http://localhost:3003/movie/create
Content-Type: application/json

{
    "nome": "Matrix",
    "sinopse": "Vivemos em um mundo dominado por máquinas e somos suas baterias.",
    "lancamento": "1993-09-10",
    "avaliacao": 8.9,
    "cartaz": "1993-12-15"
}

###
POST http://localhost:3003/actor/update
Content-Type: application/json

{
    "id": 1,
    "salary": 150000
}

###
DELETE http://localhost:3003/actor/remove/7

###
GET http://localhost:3003/actor/search-gender/query-builder?gender=male

